version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: store
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
